---
- hosts: localhost
  gather_facts: false

  vars_prompt:

    - name: x
      prompt: x
      private: false

    - name: y
      prompt: y
      private: false

  tasks:

    - name: comparators
      debug:
        msg: >
          [ {{ x }} > {{ y }}: {{ x > y }} ]
          [ {{ x }} < {{ y }}: {{ x < y }} ]
          [ {{ x }} == {{ y }}: {{ x == y }} ]
          [ {{ x }} != {{ y }}: {{ x != y }} ]
          [ {{ x }} in {{ y }}: {{ x in y }} ]
